/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netput_Netput */

#ifndef _Included_org_netput_Netput
#define _Included_org_netput_Netput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netput_Netput
 * Method:    loadSink
 * Signature: (Lorg/netput/DynProperty;)Lorg/netput/Sink;
 */
JNIEXPORT jobject JNICALL Java_org_netput_Netput_loadSink
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_netput_Netput
 * Method:    parseConfigFile
 * Signature: ([B)Lorg/netput/DynProperty;
 */
JNIEXPORT jobject JNICALL Java_org_netput_Netput_parseConfigFile
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_netput_Netput
 * Method:    parseConfigString
 * Signature: ([B)Lorg/netput/DynProperty;
 */
JNIEXPORT jobject JNICALL Java_org_netput_Netput_parseConfigString
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
