/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netput_DynProperty */

#ifndef _Included_org_netput_DynProperty
#define _Included_org_netput_DynProperty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netput_DynProperty
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_netput_DynProperty_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
