/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netput_Sink */

#ifndef _Included_org_netput_Sink
#define _Included_org_netput_Sink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netput_Sink
 * Method:    setDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_netput_Sink_setDevice
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_netput_Sink
 * Method:    setKey
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_netput_Sink_setKey
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_netput_Sink
 * Method:    flushDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_netput_Sink_flushDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_netput_Sink
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_netput_Sink_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
